#!/usr/bin/env python3
"""
The hauler's dressing markers as data, for the C++ tests.

    python3 Tools/dressing_markers.py        # rewrite Tools/dressing_markers.json

build_hauler.py spawns one AShipDressingSurface per ship.surfaces entry and
one AShipDressingKeepOut per ship.keep_outs entry; verify_level.py holds the
built level to the layout. The end-to-end dressing tests cannot load that
level -- it is regenerated on main, never committed from a branch -- so they
spawn the same markers from this file, which is exactly what generate()
exports, field for field. test_dressing_markers.py fails the moment the two
disagree, so the chain layout -> JSON -> test world has no hand-typed link
(DressingTestFixtures.h stays for the pure tests, which may lag).

It also carries the laptop's and the chart's world floor rectangles (plan
conflict 16) and where each screen stands, so a test can check the excludes
from what they are for rather than from the excludes themselves.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hauler_layout as L

PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "dressing_markers.json")


def _rect(r):
    (x0, y0), (x1, y1) = r
    return [[float(x0), float(y0)], [float(x1), float(y1)]]


def export(ship=None):
    """generate()'s dressing exports as plain JSON-ready data."""
    ship = ship or L.generate()
    return {
        "_comment": "Generated by Tools/dressing_markers.py from hauler_layout.generate(); do not edit.",
        "surfaces": [{
            "label": m.label,
            "room": m.room,
            "kind": m.kind,
            "ordinal": int(m.ordinal),
            "location": [float(v) for v in m.location],
            "yaw": float(m.yaw),
            "size": [float(v) for v in m.size],
            "back": m.back,
            "use": m.use,
            "clear": float(m.clear),
            "excludes": [_rect(r) for r in m.excludes],
        } for m in ship.surfaces],
        "keep_outs": [{
            "label": k.label,
            "lo": [float(v) for v in k.lo],
            "hi": [float(v) for v in k.hi],
        } for k in ship.keep_outs],
        "laptop": {"location": [float(v) for v in ship.laptop_location],
                   "exclude": _rect(ship.laptop_exclude)},
        "chart": {"location": [float(v) for v in ship.nav_screen_location],
                  "exclude": _rect(ship.nav_screen_exclude)},
    }


def dumps(data):
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def main():
    with open(PATH, "w") as f:
        f.write(dumps(export()))
    print("wrote " + PATH)
    return 0


if __name__ == "__main__":
    sys.exit(main())
